#!/usr/bin/env python3
"""
universal_profiles_example.py
=============================
Demonstrates the Universal Lazy Profile System using the environment loader.

This example does NOT hardcode any models. It relies entirely on the `.env` file
generated by the wizard or manually configured by the user (see `example.env`).

Prerequisites:
1. Run `python -m lollms_client.lollms_config_cli_env` to configure your bindings.
2. When prompted, ensure you add additional profiles (e.g., alias 'coder', 'vision').
3. Alternatively, copy `examples/example.env` to your project root and edit it.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from ascii_colors import ASCIIColors
from lollms_client.lollms_config_cli_env import get_client_from_env
from lollms_client import LollmsClient

def main():
    ASCIIColors.panel(
        "[bold]Universal Lazy Profiles Demo (Environment-Driven)[/bold]",
        title="[bold green]🧠 Multi-Model Architecture[/bold green]",
        border_style="green"
    )

    ASCIIColors.cyan("Loading client from environment (.env)...")
    # We only need LLM for this example, but we could load TTI/TTS as well.
    client = get_client_from_env(create_llm=True)

    ASCIIColors.green("\n✅ Client initialized!")
    ASCIIColors.magenta(f"Active LLM Alias: {client._active_llm_alias}")
    ASCIIColors.magenta(f"Active LLM Model: {client.llm.model_name}")

    # List all available LLM profiles configured in the .env file
    available_profiles = list(client.llm_profiles_registry.keys())
    ASCIIColors.cyan(f"\nAvailable LLM Profiles in registry: {available_profiles}")

    if len(available_profiles) <= 1:
        ASCIIColors.yellow("\n⚠️ Only the master profile is loaded.")
        ASCIIColors.yellow("To see the full power of this example, run the configuration wizard:")
        ASCIIColors.yellow("python -m lollms_client.lollms_config_cli_env")
        ASCIIColors.yellow("And add at least one additional LLM profile (e.g., 'coder').")
        return

    # Pick the first non-master profile to demonstrate switching
    target_alias = next((p for p in available_profiles if p != "master"), None)
    
    if target_alias:
        ASCIIColors.cyan(f"\nSwitching to profile: '{target_alias}'...")
        success = client.switch_model(target_alias)
        
        if success:
            ASCIIColors.green(f"✅ Successfully switched!")
            ASCIIColors.magenta(f"New Active LLM Alias: {client._active_llm_alias}")
            ASCIIColors.magenta(f"New Active LLM Model: {client.llm.model_name}")
            
            # Generate text using the newly activated profile
            response = client.generate_text("Write a Python one-liner to reverse a string.", temperature=0.1)
            ASCIIColors.green(f"\nResponse from '{target_alias}': {response.strip()}")
            
            # Switch back to master
            ASCIIColors.cyan("\nSwitching back to 'master' profile...")
            client.switch_model("master")
            ASCIIColors.magenta(f"Active LLM Alias: {client._active_llm_alias}")
        else:
            ASCIIColors.red(f"❌ Failed to switch to profile '{target_alias}'.")

if __name__ == "__main__":
    main()